server:
  servlet:
    context-path: /device
spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://192.168.1.91:5433/
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    name: scity_device_dev
    hikari:
      pool-name: scity-device-pool
      maximum-pool-size: 3
      max-lifetime: 600000
      idle-timeout: 300000
      connection-timeout: 30000
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  cassandra:
    keyspace-name: ks_scity_device